#!/bin/bash

# if on bootstrap
[ -d /host/var/lib/containers/storage/volumes/ironic/_data ] && echo /host/var/lib/containers/storage/volumes/ironic/_data && exit 0

# on master
find /host/var/lib/kubelet/pods/ -name metal3-shared | grep volumes/kubernetes.io~empty-dir
